### ISSUE TITLE
metadata in library mode

### ISSUE THREAD

**Issue by fruzitent** [dustinblackman/cargo-run-bin#23]
When using Cargo multi-crate workspaces, `cargo-run-bin` will read metadata only from the root `Cargo.toml`

https://github.com/dustinblackman/cargo-run-bin/blob/02a968fc095cf8afc1615ea4cd4e936b4fc1e7e6/src/metadata.rs#L77

Would it be possible to limit scope to the current crate, so they can be feature-toggled?

### Example

```rust 
// ./bin/wasm-pack/src/main.rs
fn main() {
    let packages = cargo_run_bin::metadata::get_binary_packages().unwrap();
    let binary = packages.iter().find(|e| e.package == "wasm-pack").unwrap();
    let path = cargo_run_bin::binary::install(binary.clone()).unwrap();
    cargo_run_bin::binary::run(path.clone(), std::env::args().collect()).unwrap();
}
```

```toml
# ./bin/wasm-pack/Cargo.toml
[package]
name = "wasm-pack"
version = "0.1.0"
edition = "2021"

# TODO: this does not work
# [package.metadata.bin]
# wasm-pack = { version = "0.12.1" }

[dependencies]
cargo-run-bin.workspace = true
```

```toml
# ./Cargo.toml
[workspace]
default-members = []
members = ["./bin/wasm-pack/"]
resolver = "2"

[workspace.dependencies]
cargo-run-bin = { version = "1.7.2", default-features = false }

# TODO: this does work
[workspace.metadata.bin]
wasm-pack = { version = "0.12.1" }
```

![image](https://github.com/dustinblackman/cargo-run-bin/assets/40008647/2e9f8efb-16a5-4d9d-8044-b05b3254c357)
![image](https://github.com/dustinblackman/cargo-run-bin/assets/40008647/bf55bb05-688d-4b01-a372-f55cbe7f0c3e)
