### ISSUE TITLE
Suggestion: List bins in [package.metadata] rather than [dev-dependencies]

### ISSUE THREAD

**Issue by J-M0** [dustinblackman/cargo-run-bin#3]
I'd like to propose that cargo-run-bin look for binaries in a table under `[package.metadata]` in Cargo.toml rather than `[dev-dependencies]`. Listing binaries in `[dev-dependencies]` will cause them to be compiled when running `cargo test`, leading to longer build times and compiling code that isn't used in the tests. Cargo specifically set aside the `[package.metadata]` table as a space for third-party tools to store information.

The listing could look something like this:

```toml
[package.metadata.cargo-run-bin]
cross = "0.2.1"
cargo-make = "0.35.12"
```

https://doc.rust-lang.org/cargo/reference/manifest.html#the-metadata-table
