### ISSUE TITLE
`cargo-binstall` is not used if `bins = [...]` is set

### ISSUE THREAD

**Issue by matanlurey** [dustinblackman/cargo-run-bin#32]
Example reproduction:
```toml
[workspace.metadata.bin]
taplo-cli = { version = "0.10.0", bins = ["taplo"] }
```

... to refer to the [`taplo-cli`](https://github.com/tamasfe/taplo/blob/e918c7775d75df1f0e1d73dca838e3d0a532a223/crates/taplo-cli/Cargo.toml#L63-L65) package:

```toml
[[bin]]
name = "taplo"
path = "bin/taplo.rs"
```

When I run:

```sh
cargo run --package cargo-bin -- taplo
```

I'd expect this to run the equivalent of:

```sh
cargo binstall taplo-cli
```

... but instead it builds from source, which can be lengthy, especially on a (non-cached) CI run.
